# Generated by Django 6.0.5 on 2026-05-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
