# Generated by Django 6.0.5 on 2026-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('step_amount', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('step_discount', models.PositiveIntegerField(default=5)),
                ('max_discount', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
