# Generated by Django 6.0.5 on 2026-07-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_discountscheme'),
        ('sales', '0005_remove_sale_transaction_id_sale_cashier'),
    ]

    operations = [
    ]
