# Generated by Django 6.0.5 on 2026-07-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_size_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='staff_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Staff working pool (auto-capped at 25)'),
        ),
    ]
