# Generated by Django 6.0.5 on 2026-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_staff_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='staff_stock',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
